//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LazadaOrder
    {
        public int ID { get; set; }
        public string shopName { get; set; }
        public string MemberName { get; set; }
        public string OrderNumber { get; set; }
        public string WarehouseName { get; set; }
        public string logisticsName { get; set; }
        public Nullable<System.DateTime> SingleShotTime { get; set; }
        public string orderType { get; set; }
        public Nullable<System.DateTime> deliverGoodsTime { get; set; }
        public string secondaryRemarks { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryNumber { get; set; }
        public string Receivingnumber { get; set; }
        public string address { get; set; }
        public string collectAddress { get; set; }
        public string MemberCode { get; set; }
        public string ExpressCode { get; set; }
        public Nullable<int> istijiao { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string SellRemark { get; set; }
    }
}
