//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Borrow
    {
        public int ID { get; set; }
        public string BorrowName { get; set; }
        public string BorrowerFrom { get; set; }
        public string BorrowerDep { get; set; }
        public string BorrowReason { get; set; }
        public decimal BorrowMoney { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public int BorrowState { get; set; }
        public int BorrowSettementState { get; set; }
        public string BorrowCode { get; set; }
        public string BorrowAccountID { get; set; }
        public string BorrowBank { get; set; }
        public Nullable<System.DateTime> BorrowNeedDate { get; set; }
        public string BorrowAccountName { get; set; }
        public int BorrowNextApprove { get; set; }
        public int BorrowStep { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> IsVoucher { get; set; }
        public string SpendingNumber { get; set; }
        public string SpendingCompany { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string Pz_JZMemo { get; set; }
        public string PZ_Department { get; set; }
        public string PZ_Subject { get; set; }
        public Nullable<int> PZ_Direction { get; set; }
        public string Cashier { get; set; }
        public string Company { get; set; }
    }
}
