//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_trade
    {
        public int trade_id { get; set; }
        public string trade_no { get; set; }
        public sbyte platform_id { get; set; }
        public short shop_id { get; set; }
        public short warehouse_id { get; set; }
        public sbyte warehouse_type { get; set; }
        public string src_tids { get; set; }
        public string pay_account { get; set; }
        public sbyte trade_status { get; set; }
        public sbyte check_step { get; set; }
        public int consign_status { get; set; }
        public bool trade_from { get; set; }
        public bool trade_type { get; set; }
        public sbyte delivery_term { get; set; }
        public short freeze_reason { get; set; }
        public bool refund_status { get; set; }
        public bool unmerge_mask { get; set; }
        public sbyte fenxiao_type { get; set; }
        public string fenxiao_nick { get; set; }
        public System.DateTime trade_time { get; set; }
        public System.DateTime pay_time { get; set; }
        public int delay_to_time { get; set; }
        public decimal goods_count { get; set; }
        public short goods_type_count { get; set; }
        public string single_spec_no { get; set; }
        public decimal raw_goods_count { get; set; }
        public short raw_goods_type_count { get; set; }
        public sbyte customer_type { get; set; }
        public int customer_id { get; set; }
        public string buyer_nick { get; set; }
        public sbyte id_card_type { get; set; }
        public string id_card { get; set; }
        public string receiver_name { get; set; }
        public short receiver_country { get; set; }
        public int receiver_province { get; set; }
        public int receiver_city { get; set; }
        public int receiver_district { get; set; }
        public string receiver_address { get; set; }
        public string receiver_mobile { get; set; }
        public string receiver_telno { get; set; }
        public string receiver_zip { get; set; }
        public string receiver_area { get; set; }
        public string receiver_ring { get; set; }
        public string receiver_dtb { get; set; }
        public string to_deliver_time { get; set; }
        public string pre_charge_time { get; set; }
        public string currency { get; set; }
        public sbyte is_prev_notify { get; set; }
        public short logistics_id { get; set; }
        public string logistics_no { get; set; }
        public string buyer_message { get; set; }
        public string cs_remark { get; set; }
        public sbyte remark_flag { get; set; }
        public string print_remark { get; set; }
        public short note_count { get; set; }
        public sbyte buyer_message_count { get; set; }
        public sbyte cs_remark_count { get; set; }
        public short cs_remark_change_count { get; set; }
        public decimal goods_amount { get; set; }
        public decimal post_amount { get; set; }
        public decimal other_amount { get; set; }
        public decimal discount { get; set; }
        public decimal receivable { get; set; }
        public decimal discount_change { get; set; }
        public decimal trade_prepay { get; set; }
        public decimal dap_amount { get; set; }
        public decimal cod_amount { get; set; }
        public decimal pi_amount { get; set; }
        public decimal ext_cod_fee { get; set; }
        public decimal goods_cost { get; set; }
        public decimal post_cost { get; set; }
        public decimal other_cost { get; set; }
        public decimal profit { get; set; }
        public decimal paid { get; set; }
        public decimal weight { get; set; }
        public decimal volume { get; set; }
        public decimal tax { get; set; }
        public decimal tax_rate { get; set; }
        public decimal commission { get; set; }
        public sbyte invoice_type { get; set; }
        public string invoice_title { get; set; }
        public string invoice_content { get; set; }
        public int invoice_id { get; set; }
        public int salesman_id { get; set; }
        public int sales_score { get; set; }
        public int checker_id { get; set; }
        public int fchecker_id { get; set; }
        public int checkouter_id { get; set; }
        public int split_package_num { get; set; }
        public short flag_id { get; set; }
        public int bad_reason { get; set; }
        public bool is_sealed { get; set; }
        public sbyte gift_mask { get; set; }
        public int split_from_trade_id { get; set; }
        public sbyte large_type { get; set; }
        public string stockout_no { get; set; }
        public int logistics_template_id { get; set; }
        public int sendbill_template_id { get; set; }
        public short revert_reason { get; set; }
        public short cancel_reason { get; set; }
        public bool is_unpayment_sms { get; set; }
        public int package_id { get; set; }
        public int trade_mask { get; set; }
        public string reserve { get; set; }
        public short version_id { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    }
}
