//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebms_refundable
    {
        public int ID { get; set; }
        public Nullable<int> oid { get; set; }
        public int detail_id { get; set; }
        public Nullable<int> pid { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public int typ { get; set; }
        public Nullable<System.DateTime> refundabledate { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string shop_no { get; set; }
        public string ordernumber { get; set; }
        public string wangwang { get; set; }
        public string reason { get; set; }
        public string goods_no { get; set; }
        public string goods_name { get; set; }
        public string oldcode { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> goods_amount { get; set; }
        public Nullable<decimal> share_amount { get; set; }
        public string refundablehouse { get; set; }
        public string expressnumber { get; set; }
        public string retreat_isrefund { get; set; }
        public string retreat_Isreturn { get; set; }
        public string retreat_deliverstatus { get; set; }
        public Nullable<int> returnnum { get; set; }
        public string returnhouse { get; set; }
        public Nullable<System.DateTime> sortingdate { get; set; }
        public Nullable<int> IsImport { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string ImportNumber { get; set; }
        public Nullable<int> ImportType { get; set; }
        public string shop_name { get; set; }
        public Nullable<decimal> actualjine { get; set; }
        public string express { get; set; }
        public string retreat_status { get; set; }
        public Nullable<decimal> goods_price { get; set; }
        public Nullable<int> totalqty { get; set; }
        public string housename { get; set; }
        public Nullable<int> IsInsertToNC { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
