//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PurchaseExecutiveDetails
    {
        public int ID { get; set; }
        public int Purchase_ID { get; set; }
        public double PlanNum { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Specifications { get; set; }
        public string Remarks { get; set; }
        public string Supplier { get; set; }
        public Nullable<double> ActualNum { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> offer { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public System.DateTime RequirementDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string PZ_Department { get; set; }
        public string PZ_Subject { get; set; }
        public Nullable<int> PZ_Direction { get; set; }
    }
}
