//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO_REGION
    {
        public int ID { get; set; }
        public string REGION_CODE { get; set; }
        public string REGION_NAME { get; set; }
        public Nullable<double> PARENT_ID { get; set; }
        public Nullable<double> REGION_LEVEL { get; set; }
        public Nullable<double> REGION_ORDER { get; set; }
        public string REGION_NAME_EN { get; set; }
        public string REGION_SHORTNAME_EN { get; set; }
    }
}
