//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PersonnelFile1
    {
        public int ID { get; set; }
        public string Pic { get; set; }
        public string Code { get; set; }
        public string IDnum { get; set; }
        public string NickName { get; set; }
        public string TrueName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Edu { get; set; }
        public string MaritalStatus { get; set; }
        public string HealthState { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> CanEntryTime { get; set; }
        public string PoliticsStatus { get; set; }
        public string ExpectedSalary { get; set; }
        public string CanBusinessTravel { get; set; }
        public string HouseholdRegister { get; set; }
        public string PresentAddress { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactTel { get; set; }
        public string CET { get; set; }
        public string NCRE { get; set; }
        public string OtherCertificate { get; set; }
        public string Character { get; set; }
        public string ApplyJob { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> InterviewState { get; set; }
        public string CurrentInterviewer { get; set; }
        public int InterviewStep { get; set; }
        public Nullable<int> DemandID { get; set; }
        public string Department { get; set; }
        public string Job { get; set; }
        public string School { get; set; }
        public string Profession { get; set; }
        public string Nation { get; set; }
        public string NativePlace { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
        public string HireMaster { get; set; }
        public int isZhuanzheng { get; set; }
        public Nullable<System.DateTime> zhuanzheng_date { get; set; }
        public Nullable<System.DateTime> PaySSDate { get; set; }
        public Nullable<System.DateTime> ContractFirstStartTime { get; set; }
        public Nullable<System.DateTime> ContractFirstDeadline { get; set; }
        public Nullable<System.DateTime> ContractSecondDeadline { get; set; }
        public Nullable<System.DateTime> ContractThirdDeadline { get; set; }
        public string DormitoryNum { get; set; }
        public string CupboardNun { get; set; }
        public string WorkNum { get; set; }
        public string FixedAssets { get; set; }
        public string EntryData { get; set; }
        public Nullable<int> OnJob { get; set; }
        public Nullable<int> OwnUnitsWorkYears { get; set; }
        public string Insurance { get; set; }
        public Nullable<int> WorkYears { get; set; }
        public string Memo { get; set; }
        public string SalaryCard { get; set; }
        public string online { get; set; }
        public int oid { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<double> ProbationSalary { get; set; }
        public Nullable<double> Salary { get; set; }
        public double Probation { get; set; }
        public string BirthdayType { get; set; }
    }
}
