//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CashBack
    {
        public int ID { get; set; }
        public string PostUser { get; set; }
        public string OrderNum { get; set; }
        public string VipName { get; set; }
        public string ShopName { get; set; }
        public string WangWang { get; set; }
        public string Reason { get; set; }
        public decimal BackMoney { get; set; }
        public string ApproveName { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public string AlipayName { get; set; }
        public string AlipayAccount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<int> For_Delete { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Step { get; set; }
        public string Repeat { get; set; }
        public int Method { get; set; }
        public string BackFrom { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
