//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NoTicketExpense
    {
        public int ID { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public string TheContent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ApproveTime { get; set; }
        public string PostAccountInfo { get; set; }
        public string PayAccount { get; set; }
        public string Code { get; set; }
        public Nullable<int> Del { get; set; }
    }
}
