//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Basics
    {
        public int ID { get; set; }
        public string JobNumber { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Post { get; set; }
        public Nullable<System.DateTime> TimeOfEntry { get; set; }
        public string PhoneNumber { get; set; }
        public string VXNumber { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public string IDCardNo { get; set; }
        public Nullable<System.DateTime> DateofBirthDate { get; set; }
        public string BirthdayType { get; set; }
        public string HealthState { get; set; }
        public string Education { get; set; }
        public string PoliticsStatus { get; set; }
        public string MaritalStatus { get; set; }
        public string Nation { get; set; }
        public string HouseholdRegister { get; set; }
        public string Hobby { get; set; }
        public string HukouBookType { get; set; }
        public string HukouBookAddress { get; set; }
        public string JTAddress { get; set; }
        public string UrgentName { get; set; }
        public string UrgentTelephone { get; set; }
        public string Pic { get; set; }
        public string NickName { get; set; }
        public string BloodType { get; set; }
        public string HeightS { get; set; }
        public string ISLanguages { get; set; }
        public string LanguagesGrade { get; set; }
        public string ComputerGrade { get; set; }
        public string RelativeRelation { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    }
}
