//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ManualExpressDetail
    {
        public int ID { get; set; }
        public string express { get; set; }
        public string weight { get; set; }
        public Nullable<double> MoneyAmount { get; set; }
        public int Oid { get; set; }
        public string Remarks { get; set; }
    }
}
