//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WDTshop
    {
        public int ID { get; set; }
        public string platform_id { get; set; }
        public string sub_platform_id { get; set; }
        public string shop_id { get; set; }
        public string shop_no { get; set; }
        public string shop_name { get; set; }
        public string account_id { get; set; }
        public string account_nick { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string zip { get; set; }
        public string mobile { get; set; }
        public string telno { get; set; }
    }
}
