//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_brand
    {
        public goods_brand()
        {
            this.goods_goods = new HashSet<goods_goods>();
        }
    
        public int brand_id { get; set; }
        public string brand_no { get; set; }
        public string brand_name { get; set; }
        public string remark { get; set; }
        public short sales_rate_type { get; set; }
        public int sales_rate_cycle { get; set; }
        public decimal sales_rate { get; set; }
        public short alarm_type { get; set; }
        public int alarm_days { get; set; }
        public int alarm_days1 { get; set; }
        public short is_disabled { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<goods_goods> goods_goods { get; set; }
    }
}
