//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_warehouse
    {
        public short warehouse_id { get; set; }
        public string warehouse_no { get; set; }
        public string name { get; set; }
        public short type { get; set; }
        public short sub_type { get; set; }
        public string api_key { get; set; }
        public string api_object_id { get; set; }
        public string ext_warehouse_no { get; set; }
        public short match_warehouse_id { get; set; }
        public int tag { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string division_id { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string zip { get; set; }
        public string mobile { get; set; }
        public string telno { get; set; }
        public string remark { get; set; }
        public string prop1 { get; set; }
        public string prop2 { get; set; }
        public short is_defect { get; set; }
        public int flag { get; set; }
        public int cod_logistics_id { get; set; }
        public short shop_id { get; set; }
        public short is_outer_stock { get; set; }
        public short is_outer_goods { get; set; }
        public short is_disabled { get; set; }
        public int priority { get; set; }
        public decimal coordinates_x { get; set; }
        public decimal coordinates_y { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
