//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ExpressIndemnityApprove
    {
        public int ID { get; set; }
        public string ApproveName { get; set; }
        public Nullable<System.DateTime> ApproveData { get; set; }
        public string State { get; set; }
        public int Step { get; set; }
        public string Memo { get; set; }
        public int EID { get; set; }
        public Nullable<double> Money { get; set; }
        public string Address { get; set; }
        public string MoneyWhereAbout { get; set; }
    }
}
