//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FundAllot
    {
        public int ID { get; set; }
        public string PostUser { get; set; }
        public string Department { get; set; }
        public string CompanyIn { get; set; }
        public string TheReceivingBank { get; set; }
        public string AccountNumber { get; set; }
        public string CompanyOut { get; set; }
        public string ThePaymentBank { get; set; }
        public string PaymentNumber { get; set; }
        public int Status { get; set; }
        public string UseOfProceeds { get; set; }
        public System.DateTime PostTime { get; set; }
        public int Step { get; set; }
        public decimal theMoney { get; set; }
        public string FundAllotCode { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> IsPzStatus { get; set; }
        public string Pz_FundMemo { get; set; }
        public string PZ_Department { get; set; }
        public string PZ_Subject { get; set; }
        public Nullable<int> PZ_Direction { get; set; }
    }
}
