//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ManualOrder
    {
        public int ID { get; set; }
        public string order_type_code { get; set; }
        public string platform_code { get; set; }
        public string shop_code { get; set; }
        public string express_code { get; set; }
        public string warehouse_code { get; set; }
        public string vip_code { get; set; }
        public string vip_name { get; set; }
        public string receiver_name { get; set; }
        public string receiver_address { get; set; }
        public string receiver_mobile { get; set; }
        public string receiver_phone { get; set; }
        public string receiver_province { get; set; }
        public string receiver_city { get; set; }
        public string receiver_district { get; set; }
        public string deal_datetime { get; set; }
        public string payment { get; set; }
        public string buyer_memo { get; set; }
        public string seller_memo { get; set; }
        public string business_man_code { get; set; }
        public int orderstatus { get; set; }
    }
}
