//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Purchase
    {
        public int ID { get; set; }
        public string ApplyName { get; set; }
        public string ApplyDepartment { get; set; }
        public string ApplyReason { get; set; }
        public string PurchaseOddNum { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string Payment { get; set; }
        public string Warehouse { get; set; }
        public Nullable<decimal> CopelPay { get; set; }
        public string paymentMode { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public int IsDelete { get; set; }
        public Nullable<int> Ispayment { get; set; }
        public Nullable<int> IsReceived { get; set; }
        public Nullable<decimal> ActualPay { get; set; }
        public string ApproveFirst { get; set; }
    }
}
