//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ExchangeDetail
    {
        public int ID { get; set; }
        public int ExchangeCenterId { get; set; }
        public string SendProductCode { get; set; }
        public string SendProductName { get; set; }
        public int SendProductNum { get; set; }
        public string NeedProductName { get; set; }
        public int NeedProductNum { get; set; }
        public string NeedProductCode { get; set; }
        public Nullable<int> WarhouseNum { get; set; }
    }
}
