//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReturnToStorage
    {
        public int ID { get; set; }
        public string Retreat_expressName { get; set; }
        public string Retreat_expressNumber { get; set; }
        public string CollectName { get; set; }
        public string CollectAddress { get; set; }
        public string receivermobile { get; set; }
        public string Retreat_Warehouse { get; set; }
        public string Retreat_Remarks { get; set; }
        public Nullable<int> isSorting { get; set; }
        public string SortingName { get; set; }
        public string ModularName { get; set; }
        public string yuan_expressNumber { get; set; }
        public Nullable<System.DateTime> GoodsReceiptDate { get; set; }
        public string GoodsReceiptName { get; set; }
        public Nullable<System.DateTime> SortingDate { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string ExternalSingle { get; set; }
        public Nullable<System.DateTime> ExternalSingleTime { get; set; }
        public string BoxNum { get; set; }
    }
}
