//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_Transfer_Remark_Log
    {
        public int ID { get; set; }
        public string Warehouse_no { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public string Remarks { get; set; }
        public string goodsList { get; set; }
        public string Reason { get; set; }
    }
}
