//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Warehouses_Backups
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string type_name { get; set; }
        public string note { get; set; }
        public string contact_name { get; set; }
        public string contact_phone { get; set; }
        public string contact_mobile { get; set; }
        public string area_name { get; set; }
        public string address { get; set; }
    }
}
