//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReturnToStoragelet
    {
        public int ID { get; set; }
        public string item_code { get; set; }
        public string item_name { get; set; }
        public string Simplename { get; set; }
        public Nullable<int> qty { get; set; }
        public int qualified { get; set; }
        public int Unqualified { get; set; }
        public Nullable<int> Notreceived { get; set; }
        public int Pid { get; set; }
        public string Remarks { get; set; }
        public string UnitName { get; set; }
        public string PrintNO_qualified { get; set; }
        public string PrintNO_unqualified { get; set; }
    }
}
