//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ToRegularWorker
    {
        public int ID { get; set; }
        public string PostName { get; set; }
        public System.DateTime PostTime { get; set; }
        public string ProbationJob { get; set; }
        public string Job { get; set; }
        public System.DateTime StartProbationTime { get; set; }
        public System.DateTime EndProbationTime { get; set; }
        public string ApplyContent { get; set; }
        public string CurrentApprove { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public int isDelete { get; set; }
        public double Salary { get; set; }
    }
}
