//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dict_platform
    {
        public dict_platform()
        {
            this.sys_shop = new HashSet<sys_shop>();
        }
    
        public short platform_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<sys_shop> sys_shop { get; set; }
    }
}
