//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WDTSoOrderEntities : DbContext
    {
        public WDTSoOrderEntities()
            : base("name=WDTSoOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dict_platform> dict_platform { get; set; }
        public DbSet<ebms_refund_tonc> ebms_refund_tonc { get; set; }
        public DbSet<ebms_refundable> ebms_refundable { get; set; }
        public DbSet<ebms_returnstorage> ebms_returnstorage { get; set; }
        public DbSet<ebms_returnstorage_fictitious> ebms_returnstorage_fictitious { get; set; }
        public DbSet<fictitious> fictitious { get; set; }
        public DbSet<goods_brand> goods_brand { get; set; }
        public DbSet<goods_class> goods_class { get; set; }
        public DbSet<goods_goods> goods_goods { get; set; }
        public DbSet<goods_spec> goods_spec { get; set; }
        public DbSet<log_Record> log_Record { get; set; }
        public DbSet<NC_close> NC_close { get; set; }
        public DbSet<NC_sales> NC_sales { get; set; }
        public DbSet<NC_SoSale_Remark_Log> NC_SoSale_Remark_Log { get; set; }
        public DbSet<NC_Transfer_Remark_Log> NC_Transfer_Remark_Log { get; set; }
        public DbSet<NCGeneral_to_WDTOtherBill_Log> NCGeneral_to_WDTOtherBill_Log { get; set; }
        public DbSet<NCTranfer_To_WDTOther_Log> NCTranfer_To_WDTOther_Log { get; set; }
        public DbSet<sale_ToNC_Log> sale_ToNC_Log { get; set; }
        public DbSet<sale_zoAmount_trade_order> sale_zoAmount_trade_order { get; set; }
        public DbSet<sales_trade_close> sales_trade_close { get; set; }
        public DbSet<sales_trade_order> sales_trade_order { get; set; }
        public DbSet<sales_trade_orders> sales_trade_orders { get; set; }
        public DbSet<SettlementPriceList> SettlementPriceList { get; set; }
        public DbSet<sql_sostockout_detail> sql_sostockout_detail { get; set; }
        public DbSet<sql_sostockout_detail_fictitious> sql_sostockout_detail_fictitious { get; set; }
        public DbSet<stock_transfer_details> stock_transfer_details { get; set; }
        public DbSet<stockin_order_details> stockin_order_details { get; set; }
        public DbSet<stockout_order_details> stockout_order_details { get; set; }
        public DbSet<StockOut_ToNC_Log> StockOut_ToNC_Log { get; set; }
        public DbSet<sys_warehouse> sys_warehouse { get; set; }
        public DbSet<SysLog> SysLog { get; set; }
        public DbSet<temp_test> temp_test { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<TressferBill_ToNC> TressferBill_ToNC { get; set; }
        public DbSet<WDTDiaoBo_to_NCTransfer_Log> WDTDiaoBo_to_NCTransfer_Log { get; set; }
        public DbSet<WDTStockout_to_NCStockout_Log> WDTStockout_to_NCStockout_Log { get; set; }
        public DbSet<sys_shop> sys_shop { get; set; }
        public DbSet<Userid> Userid { get; set; }
        public DbSet<WDTStockin_to_NCStockin_Log> WDTStockin_to_NCStockin_Log { get; set; }
    }
}
