//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCGeneral_to_WDTOtherBill_Log
    {
        public int ID { get; set; }
        public string NCGeneralCode { get; set; }
        public string WDTOtherInCode { get; set; }
        public Nullable<System.DateTime> CreateTme { get; set; }
        public Nullable<int> IsSuccess { get; set; }
        public string FailReaon { get; set; }
        public string Warehouse_no { get; set; }
        public Nullable<int> IsStockOut { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IsOtherBill { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string Outer_no { get; set; }
    }
}
