//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Basics_WorkExperience
    {
        public int ID { get; set; }
        public Nullable<int> BasicsID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CorporateName { get; set; }
        public string Department { get; set; }
        public string Post { get; set; }
        public string QuitReason { get; set; }
        public string WitnessName { get; set; }
        public string PhoneNumber { get; set; }
        public string RelativeRelation { get; set; }
    }
}
