//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_trade_orders
    {
        public int ID { get; set; }
        public int trade_id { get; set; }
        public int rec_id { get; set; }
        public string src_oid { get; set; }
        public string src_tid { get; set; }
        public string src_tids { get; set; }
        public string trade_no { get; set; }
        public Nullable<int> platform_id { get; set; }
        public string platform_name { get; set; }
        public string shop_no { get; set; }
        public string shop_name { get; set; }
        public string warehouse_no { get; set; }
        public string warehouse_name { get; set; }
        public Nullable<int> trade_type { get; set; }
        public Nullable<int> trade_status { get; set; }
        public Nullable<System.DateTime> trade_time { get; set; }
        public Nullable<System.DateTime> pay_time { get; set; }
        public string buyer_nick { get; set; }
        public Nullable<int> trade_from { get; set; }
        public Nullable<int> delivery_term { get; set; }
        public string stockout_no { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> gift_type { get; set; }
        public Nullable<double> num { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> actual_num { get; set; }
        public Nullable<decimal> order_price { get; set; }
        public Nullable<decimal> share_price { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> share_amount { get; set; }
        public Nullable<decimal> share_post { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<double> tax_rate { get; set; }
        public string goods_name { get; set; }
        public string goods_no { get; set; }
        public Nullable<decimal> commission { get; set; }
        public string spec_name { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> Stime { get; set; }
        public Nullable<System.DateTime> Etime { get; set; }
        public Nullable<int> IsImport { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.DateTime> TimeAdd { get; set; }
        public Nullable<int> typ { get; set; }
        public Nullable<System.DateTime> ExcelDate { get; set; }
        public Nullable<int> IsInsertToNC { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Reason { get; set; }
    }
}
