//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_trade_order
    {
        public int rec_id { get; set; }
        public int trade_id { get; set; }
        public int spec_id { get; set; }
        public sbyte platform_id { get; set; }
        public string src_oid { get; set; }
        public int suite_id { get; set; }
        public string src_tid { get; set; }
        public bool gift_type { get; set; }
        public sbyte refund_status { get; set; }
        public sbyte guarantee_mode { get; set; }
        public sbyte delivery_term { get; set; }
        public string bind_oid { get; set; }
        public decimal num { get; set; }
        public decimal price { get; set; }
        public decimal actual_num { get; set; }
        public decimal refund_num { get; set; }
        public decimal order_price { get; set; }
        public decimal share_price { get; set; }
        public decimal adjust { get; set; }
        public decimal discount { get; set; }
        public decimal share_amount { get; set; }
        public decimal share_amount2 { get; set; }
        public decimal share_post { get; set; }
        public decimal paid { get; set; }
        public decimal tax_rate { get; set; }
        public string goods_name { get; set; }
        public int goods_id { get; set; }
        public string goods_no { get; set; }
        public string spec_name { get; set; }
        public string spec_no { get; set; }
        public string spec_code { get; set; }
        public string suite_no { get; set; }
        public string suite_name { get; set; }
        public decimal suite_num { get; set; }
        public decimal suite_amount { get; set; }
        public decimal suite_discount { get; set; }
        public bool is_print_suite { get; set; }
        public string api_goods_name { get; set; }
        public string api_spec_name { get; set; }
        public decimal weight { get; set; }
        public decimal commission { get; set; }
        public sbyte goods_type { get; set; }
        public int flag { get; set; }
        public bool is_zero_cost { get; set; }
        public sbyte stock_reserved { get; set; }
        public sbyte is_consigned { get; set; }
        public bool large_type { get; set; }
        public sbyte invoice_type { get; set; }
        public string invoice_content { get; set; }
        public int from_mask { get; set; }
        public sbyte is_received { get; set; }
        public bool is_master { get; set; }
        public int cid { get; set; }
        public string remark { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
    }
}
