//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockin_order_details
    {
        public int ID { get; set; }
        public int stockin_id { get; set; }
        public string spec_no { get; set; }
        public Nullable<decimal> goods_count { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> cost_price { get; set; }
        public Nullable<decimal> src_price { get; set; }
        public Nullable<decimal> tax_price { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public string remark { get; set; }
        public string brand_no { get; set; }
        public string brand_name { get; set; }
        public string goods_name { get; set; }
        public string goods_no { get; set; }
        public string spec_name { get; set; }
        public string spec_code { get; set; }
        public Nullable<System.DateTime> TimeAdd { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int IsImport { get; set; }
        public string StockOutCode { get; set; }
        public System.DateTime STime { get; set; }
        public System.DateTime Etime { get; set; }
        public Nullable<int> IsInsertToNC { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> stockin_time { get; set; }
        public string warehouse_no { get; set; }
        public string order_no { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
        public string stockin_reason { get; set; }
        public Nullable<int> order_type { get; set; }
        public string order_type_name { get; set; }
        public Nullable<decimal> goods_amount { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<decimal> post_fee { get; set; }
        public Nullable<decimal> other_fee { get; set; }
        public Nullable<int> logistics_type { get; set; }
        public Nullable<System.DateTime> check_time { get; set; }
        public string src_order_no { get; set; }
        public int rec_id { get; set; }
        public string Reason { get; set; }
    }
}
