//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_transfer_details
    {
        public int ID { get; set; }
        public Nullable<int> transfer_id { get; set; }
        public string transfer_no { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> mode { get; set; }
        public string from_warehouse_no { get; set; }
        public string to_warehouse_no { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> logistics_type { get; set; }
        public string logistics_no { get; set; }
        public string logistics_name { get; set; }
        public string logistics_code { get; set; }
        public string spec_no { get; set; }
        public string goods_no { get; set; }
        public string spec_code { get; set; }
        public string spec_name { get; set; }
        public string barcode { get; set; }
        public string from_position { get; set; }
        public string to_position { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<decimal> stock_num { get; set; }
        public Nullable<decimal> num { get; set; }
        public Nullable<decimal> out_num { get; set; }
        public Nullable<decimal> in_num { get; set; }
        public string unit_name { get; set; }
        public string aux_unit_name { get; set; }
        public Nullable<decimal> aux_num { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> TimeAdd { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> IsImport { get; set; }
        public string StockOutCode { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<System.DateTime> Etime { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> IsInsertToNC { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Reason { get; set; }
        public string goods_name { get; set; }
    }
}
