//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AliSumai
    {
        public int ID { get; set; }
        public string OrderNO { get; set; }
        public string TransactionNO { get; set; }
        public string OrderState { get; set; }
        public string Platform { get; set; }
        public string BuyerAccount { get; set; }
        public string BuyerName { get; set; }
        public string Currency { get; set; }
        public Nullable<double> OrderMoney { get; set; }
        public string PayType { get; set; }
        public string RetreatReason { get; set; }
        public Nullable<double> LogisticsCost { get; set; }
        public string OrderMemo { get; set; }
        public string PickingMemo { get; set; }
        public string SellerMemo { get; set; }
        public string Email { get; set; }
        public string PackageNO { get; set; }
        public string LogisticsType { get; set; }
        public string BuyerSpecifiedLogistics { get; set; }
        public string MailNO { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string DeliverTime { get; set; }
        public string ShopName { get; set; }
        public int IsSubmit { get; set; }
        public int IsDown { get; set; }
        public System.DateTime PostTime { get; set; }
        public string PostName { get; set; }
    }
}
