//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AssetsTransferRecord
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Department { get; set; }
        public string Place { get; set; }
        public string Responsible { get; set; }
        public string TransferOwner { get; set; }
        public string TransferDepartment { get; set; }
        public string TransferPlace { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string UserName { get; set; }
        public string TransferResponsible { get; set; }
        public string Memo { get; set; }
        public string PostUserName { get; set; }
        public string Receiver { get; set; }
        public Nullable<int> ApplyID { get; set; }
        public string TransferType { get; set; }
    }
}
