//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BorrowSettementRecord
    {
        public int ID { get; set; }
        public string BorrowCode { get; set; }
        public string ReunCode { get; set; }
        public string BorrowType { get; set; }
        public string SettementUser { get; set; }
        public decimal BorrowCost { get; set; }
        public decimal SettementCost { get; set; }
        public decimal SurplusCost { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SettementDate { get; set; }
    }
}
