//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CollectionQuidcoStatus
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string OrdersCode { get; set; }
        public string OrdersFrom { get; set; }
        public string Type { get; set; }
        public string GoodsMoney { get; set; }
        public string CollectionMoney { get; set; }
        public string SettlementStaus { get; set; }
        public string ProductName { get; set; }
        public string OverTime { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Branch { get; set; }
        public string DeliverySite { get; set; }
        public string DeliveryParentCompany { get; set; }
        public string Deliverys { get; set; }
        public string DeliveryScanTime { get; set; }
        public string ReturnSignInTime { get; set; }
        public string SendSite { get; set; }
        public string SendSiteParentComPany { get; set; }
        public string Sends { get; set; }
        public string SignInTime { get; set; }
        public string PaymentWay { get; set; }
        public string PayChargeDay { get; set; }
        public string AdvanceStatus { get; set; }
        public string FinanceQuidcoDate { get; set; }
    }
}
