//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CollectionServiceCost
    {
        public int ID { get; set; }
        public string OrdersCode { get; set; }
        public string Number { get; set; }
        public string OrdersFrom { get; set; }
        public string StartDate { get; set; }
        public string Weight { get; set; }
        public string ReceiveAddress { get; set; }
        public string Receives { get; set; }
        public string CollectionMony { get; set; }
        public string PurchasePrice { get; set; }
        public string ReceivedCollectionMony { get; set; }
        public string ExpressStatus { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string PayableServiceMony { get; set; }
        public string PayableProcedureMony { get; set; }
        public string ReceivablePurchasePrice { get; set; }
        public string Seizes { get; set; }
        public string ReceiveBranch { get; set; }
        public string ReceiveCompany { get; set; }
        public string ReceivableServiceMony { get; set; }
        public string PayableServiceMonyByReceived { get; set; }
        public string PayableProcedureMonyByReceived { get; set; }
        public string ReceivableCost { get; set; }
        public string ReceivableServiceMonyCenter { get; set; }
        public string ReceivableCenterCost { get; set; }
        public string SendCompany { get; set; }
        public string SendBranch { get; set; }
        public string Sends { get; set; }
        public string ReceivableServiceMonyBySend { get; set; }
        public string ReceivableCostBySend { get; set; }
        public string PayStatus { get; set; }
        public string SettlementDate { get; set; }
    }
}
