//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Data_DayShopSales
    {
        public string DayValue { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public double Total { get; set; }
        public int Count { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> CashBack { get; set; }
        public Nullable<double> Retreat { get; set; }
    }
}
