//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ElectronicInvoiceEnclosure
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public string uploadName { get; set; }
    }
}
