//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ExpressIndemnity
    {
        public int ID { get; set; }
        public string PostUserName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderNum { get; set; }
        public string wangwang { get; set; }
        public string RetreatReason { get; set; }
        public string ShopName { get; set; }
        public string RetreatExpressNum { get; set; }
        public string Memo { get; set; }
        public string State { get; set; }
        public Nullable<double> OrderMoney { get; set; }
        public string Type { get; set; }
        public string Second { get; set; }
        public string Pic { get; set; }
        public string CurrentApproveName { get; set; }
        public int IsDelete { get; set; }
        public string ExpressName { get; set; }
        public Nullable<double> IndemnityMoney { get; set; }
        public string Address { get; set; }
        public string MoneyWhereAbout { get; set; }
        public string Module { get; set; }
        public string Repeat { get; set; }
    }
}
