//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Freeze
    {
        public int ID { get; set; }
        public string shopName { get; set; }
        public string alipay { get; set; }
        public decimal freezeMoney { get; set; }
        public string freezeReason { get; set; }
        public string remark { get; set; }
        public string userName { get; set; }
        public System.DateTime datetime { get; set; }
        public int state { get; set; }
        public int isDelete { get; set; }
        public Nullable<decimal> usedMoney { get; set; }
        public Nullable<decimal> surplusMoney { get; set; }
        public int Step { get; set; }
    }
}
