//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Generalize
    {
        public int ID { get; set; }
        public string Guid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PlatformCode { get; set; }
        public string PostUser { get; set; }
        public string StoreName { get; set; }
        public string OrderNumber { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CommissionCost { get; set; }
        public string DKUserMessage { get; set; }
        public string AliNumber { get; set; }
        public string BankNumber { get; set; }
        public string TenPay { get; set; }
        public string IsCheck { get; set; }
        public string OrderType { get; set; }
        public string PayCommissionNumber { get; set; }
        public string Memo { get; set; }
        public string BorrowCode { get; set; }
        public string ResponsibleName { get; set; }
        public string IsSend { get; set; }
        public string IsCancel { get; set; }
        public string PlatformFlag { get; set; }
        public string WarhouseName { get; set; }
        public string UploadName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> IsDispose { get; set; }
    }
}
