//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GH_List
    {
        public int ID { get; set; }
        public string GH_User { get; set; }
        public string GH_Hospital { get; set; }
        public string GH_Dept { get; set; }
        public string GH_Time { get; set; }
        public string GH_Doctor { get; set; }
        public int GH_Status { get; set; }
        public string GH_Tel { get; set; }
        public string GH_IDCode { get; set; }
        public string GH_Memo { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public string WXCode { get; set; }
        public Nullable<int> Oid { get; set; }
    }
}
