//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GH_Doctor_Record
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string OrderDay { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> OrderInterval { get; set; }
        public Nullable<int> DoctorID { get; set; }
    }
}
