//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_goodsGY
    {
        public int ID { get; set; }
        public System.DateTime create_date { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public Nullable<double> weight { get; set; }
        public string combine { get; set; }
        public string simple_name { get; set; }
        public string category_code { get; set; }
        public string category_name { get; set; }
        public string supplier_code { get; set; }
        public string item_unit_code { get; set; }
        public Nullable<double> package_point { get; set; }
        public Nullable<double> sales_point { get; set; }
        public Nullable<decimal> sales_price { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> agent_price { get; set; }
        public Nullable<decimal> cost_price { get; set; }
        public string stock_status_code { get; set; }
        public string pic_url { get; set; }
        public string del { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string create_Name { get; set; }
        public string Manufactor { get; set; }
        public string Specifications { get; set; }
        public string classify { get; set; }
        public string isexamine { get; set; }
        public string TheCode { get; set; }
        public string ExamineName { get; set; }
        public Nullable<int> splitNumber { get; set; }
        public string barcode { get; set; }
    }
}
