//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Intercept
    {
        public int ID { get; set; }
        public string PostUSer { get; set; }
        public string OrderNumber { get; set; }
        public string NewOrderNumber { get; set; }
        public string Receiver { get; set; }
        public string ExpressName { get; set; }
        public string MailNo { get; set; }
        public string AddressMessage { get; set; }
        public string Address { get; set; }
        public string TelPhone { get; set; }
        public int Status { get; set; }
        public string Memo { get; set; }
        public string Postalcode { get; set; }
        public string Phone { get; set; }
        public string Warhouse { get; set; }
        public string Reson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Step { get; set; }
        public int IsDelete { get; set; }
        public string LoadWarhouse { get; set; }
        public string LoadExpressName { get; set; }
        public string LoadAddress { get; set; }
        public string SystemRemark { get; set; }
        public string VipCode { get; set; }
        public string VipName { get; set; }
        public string StoreCode { get; set; }
        public string SingleTime { get; set; }
        public string NextApproveName { get; set; }
    }
}
