//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InterceptLogistics
    {
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public string ExpressName { get; set; }
        public string ExpressNumber { get; set; }
        public decimal OrderMoney { get; set; }
        public int FinanceApproveStatus { get; set; }
        public Nullable<int> FinanceApproveUser { get; set; }
        public Nullable<System.DateTime> FinanceApproveTime { get; set; }
        public string FinanceReason { get; set; }
        public int ExpressApproveStatus { get; set; }
        public Nullable<int> ExpressApproveUser { get; set; }
        public Nullable<System.DateTime> ExpressApproveTime { get; set; }
        public string ExpressReason { get; set; }
        public int WarehouseApproveStatus { get; set; }
        public Nullable<int> WarehouseApproveUser { get; set; }
        public Nullable<System.DateTime> WarehouseApproveTime { get; set; }
        public string WarehouseReason { get; set; }
        public string Remark { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Del { get; set; }
    }
}
