//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Joined
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string PostDepartment { get; set; }
        public string Nickname { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Tel { get; set; }
        public string PostUser { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public string Department { get; set; }
        public string SetGroup { get; set; }
        public string Job { get; set; }
        public string IdcardAddress { get; set; }
        public string Address { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyTel { get; set; }
        public string Information { get; set; }
        public string Memo { get; set; }
        public string FirstApprove { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public bool DataUserRegister { get; set; }
        public bool DataPost { get; set; }
        public bool DataResult { get; set; }
        public bool DataIdcard { get; set; }
        public bool DataQualifications { get; set; }
        public bool DataPhoto { get; set; }
        public bool DataDrivingLicense { get; set; }
        public bool DataExaminationReport { get; set; }
        public int IsDelete { get; set; }
        public int PID { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
        public double Probation { get; set; }
        public Nullable<System.DateTime> ContractFirstStartTime { get; set; }
        public Nullable<System.DateTime> ContractFirstDeadline { get; set; }
        public Nullable<double> ProbationSalary { get; set; }
        public Nullable<double> MinSalary { get; set; }
        public Nullable<double> MaxSalary { get; set; }
    }
}
