//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LossReport
    {
        public int ID { get; set; }
        public string PostUser { get; set; }
        public string Department { get; set; }
        public string Shop { get; set; }
        public string Code { get; set; }
        public int Status { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Step { get; set; }
        public string ApproveFirst { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<int> IsPzStatus { get; set; }
        public string PzMemo { get; set; }
        public Nullable<int> IsAllowdelete { get; set; }
        public string Warehouse { get; set; }
    }
}
