//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ManualExpress
    {
        public int ID { get; set; }
        public string ApplyName { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string ApplyCompany { get; set; }
        public string ApplyShop { get; set; }
        public string EntryType { get; set; }
        public string Reason { get; set; }
        public Nullable<int> votes { get; set; }
        public string OtherCompanyName { get; set; }
        public string OtherCompanyLibrary { get; set; }
        public string LibraryAddress { get; set; }
        public string LibraryPhone { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<int> Isdelete { get; set; }
        public string DetailedAddress { get; set; }
    }
}
