//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MutuallyCost
    {
        public int ID { get; set; }
        public string ComPany { get; set; }
        public string SuperiorComPany { get; set; }
        public string SettlementDate { get; set; }
        public string Number { get; set; }
        public string ReceiveCompany { get; set; }
        public string ReceiveCompanyName { get; set; }
        public string CostCode { get; set; }
        public string CostName { get; set; }
        public string Weight { get; set; }
        public string Cost { get; set; }
        public string InputDate { get; set; }
        public string SignInDate { get; set; }
        public string SendCompany { get; set; }
        public string SendCompanyName { get; set; }
        public string Receives { get; set; }
        public string ReceivesPhone { get; set; }
        public string ReceivesAdress { get; set; }
    }
}
