//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrderList
    {
        public int ID { get; set; }
        public string code { get; set; }
        public string order_type_name { get; set; }
        public string platform_code { get; set; }
        public System.DateTime createtime { get; set; }
        public string dealtime { get; set; }
        public string paytime { get; set; }
        public string cod { get; set; }
        public string approve { get; set; }
        public string delivery_state { get; set; }
        public string warehouse_code { get; set; }
        public string warehouse_name { get; set; }
        public string shop_code { get; set; }
        public string shop_name { get; set; }
        public string express_code { get; set; }
        public string express_name { get; set; }
        public string buyer_memo { get; set; }
        public string seller_memo { get; set; }
        public string seller_memo_late { get; set; }
        public string vip_code { get; set; }
        public string vip_name { get; set; }
        public string receiver_name { get; set; }
        public string receiver_phone { get; set; }
        public string receiver_mobile { get; set; }
        public string receiver_zip { get; set; }
        public string receiver_area { get; set; }
        public string receiver_address { get; set; }
        public string payCode { get; set; }
        public string vipIdCard { get; set; }
        public string vipRealName { get; set; }
        public string vipEmail { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public decimal post_fee { get; set; }
        public Nullable<decimal> discount_fee { get; set; }
        public Nullable<decimal> payment { get; set; }
        public string qty { get; set; }
        public string weight_origin { get; set; }
        public Nullable<decimal> post_cost { get; set; }
        public string mail_no { get; set; }
        public string platform_flag { get; set; }
        public string catename { get; set; }
        public string owner { get; set; }
        public string tags { get; set; }
        public string lastfollow { get; set; }
        public string lastfollowtime { get; set; }
        public string cancle { get; set; }
        public Nullable<int> Status_CashBack { get; set; }
        public Nullable<int> Status_Retreat { get; set; }
        public Nullable<int> Status_ExpressIndemnity { get; set; }
        public Nullable<int> ExchangeStatus { get; set; }
        public Nullable<int> ReissueStatus { get; set; }
        public Nullable<int> IsGeneralize { get; set; }
    }
}
