//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaymentProduct
    {
        public int ID { get; set; }
        public int ReunId { get; set; }
        public string Abstract { get; set; }
        public int Num { get; set; }
        public decimal Price { get; set; }
        public string Type { get; set; }
        public string StoreName { get; set; }
        public string PZ_Department { get; set; }
        public string PZ_Subject { get; set; }
        public Nullable<int> PZ_Direction { get; set; }
        public string PZ_Department1 { get; set; }
        public string PZ_Subject1 { get; set; }
        public Nullable<int> PZ_Direction1 { get; set; }
    }
}
