//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductCodeGenerateDetails
    {
        public int ID { get; set; }
        public string CpCode { get; set; }
        public string CpName { get; set; }
        public string CpSimpleName { get; set; }
        public Nullable<decimal> CpPrice { get; set; }
        public Nullable<int> CpNumber { get; set; }
        public Nullable<double> CpWeight { get; set; }
        public Nullable<int> Oid { get; set; }
    }
}
