//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PurchaseFinance
    {
        public int ID { get; set; }
        public Nullable<decimal> needpay { get; set; }
        public string PurchaseOddNum { get; set; }
        public Nullable<decimal> payment { get; set; }
        public string paymentName { get; set; }
        public Nullable<int> ispayment { get; set; }
        public string paymentaccounts { get; set; }
        public string paymenmode { get; set; }
        public Nullable<int> isFinanceToexamine { get; set; }
        public string FinanceToexamineName { get; set; }
        public Nullable<System.DateTime> FinanceToexaminedate { get; set; }
        public Nullable<System.DateTime> paymendate { get; set; }
        public string ApplyRemarks { get; set; }
        public string FinanceToexaminRemarks { get; set; }
        public string paymenRemarks { get; set; }
        public string ApplyName { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> IsDelte { get; set; }
        public string Pz_Memo { get; set; }
        public Nullable<int> Is_PzStatus { get; set; }
    }
}
