//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PZ_BS
    {
        public int ID { get; set; }
        public string PZ_OrderNum { get; set; }
        public string PZ_Summary { get; set; }
        public string PZ_Subject { get; set; }
        public string PZ_Department { get; set; }
        public System.DateTime PZ_Time { get; set; }
        public Nullable<decimal> PZ_Money { get; set; }
        public Nullable<int> PZ_Direction { get; set; }
    }
}
