//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Quit
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string PostUser { get; set; }
        public System.DateTime PostTime { get; set; }
        public string PostDepartment { get; set; }
        public string Reason { get; set; }
        public System.DateTime QuitTime { get; set; }
        public string AssetsCode { get; set; }
        public string WorkAccount { get; set; }
        public string BorrowCode { get; set; }
        public string WageAccount { get; set; }
        public string WageAccountName { get; set; }
        public string WageBank { get; set; }
        public string Memo { get; set; }
        public string FirstApprove { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public int IsDelete { get; set; }
    }
}
