//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Reissue
    {
        public int ID { get; set; }
        public string OrderCode { get; set; }
        public string NewOrderCode { get; set; }
        public string VipName { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string WarhouseName { get; set; }
        public string ExpressName { get; set; }
        public string OrderType { get; set; }
        public string SingleTime { get; set; }
        public string ReceivingName { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string TelPhone { get; set; }
        public string VipCode { get; set; }
        public string Address { get; set; }
        public string SalesRemark { get; set; }
        public string BuyRemark { get; set; }
        public int Step { get; set; }
        public int Status { get; set; }
        public string BusinessName { get; set; }
        public string AddressMessage { get; set; }
        public System.DateTime CreatDate { get; set; }
        public string PostUser { get; set; }
        public string SystemRemark { get; set; }
        public int IsDelete { get; set; }
        public string DraftName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string ReissueReson { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderSCode { get; set; }
        public string ISReissue { get; set; }
        public Nullable<System.DateTime> ISReissueDate { get; set; }
        public string ReissueName { get; set; }
    }
}
