//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReturnToStorageBlending
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string OrderNumber { get; set; }
        public string CollectExpressName { get; set; }
        public string CollectExpressNumber { get; set; }
        public string ShopName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> SurplusProductNumber { get; set; }
        public Nullable<int> IsBlending { get; set; }
        public Nullable<System.DateTime> BlendingDate { get; set; }
        public string BlendingName { get; set; }
        public string AccountType { get; set; }
        public Nullable<decimal> Accounts { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string AccountsTypenumber { get; set; }
    }
}
