//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RetreatPayment
    {
        public int ID { get; set; }
        public string PaymentAccounts { get; set; }
        public string PaymentAccountsName { get; set; }
        public string ShopName { get; set; }
        public string IsBlending { get; set; }
    }
}
