//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RulesNotice
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateName { get; set; }
        public string Contents { get; set; }
        public string Power { get; set; }
        public string Type { get; set; }
        public string IsDelete { get; set; }
    }
}
