//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TransFerAdjustCost
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string LargePackageNumber { get; set; }
        public string OldCostHappenDay { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string OldTransportWay { get; set; }
        public string OldConsigneeComPany { get; set; }
        public string OldConsigneeComPanyName { get; set; }
        public string OldStartCity { get; set; }
        public string OldStartCityName { get; set; }
        public string OldSendComPany { get; set; }
        public string OldSendComPanyName { get; set; }
        public string OldDestinationCity { get; set; }
        public string OldDestinationCityName { get; set; }
        public string OldActualWeight { get; set; }
        public string OldBubbleWeight { get; set; }
        public string OldSettlementWeight { get; set; }
        public string OldTransferCost { get; set; }
        public string NewCostHappenDay { get; set; }
        public string NewTransportWay { get; set; }
        public string NewStartCity { get; set; }
        public string NewStartCityName { get; set; }
        public string NewSendComPany { get; set; }
        public string NewSendComPanyName { get; set; }
        public string NewDestination { get; set; }
        public string NewDestinationName { get; set; }
        public string NewDestinationCity { get; set; }
        public string NewDestinationCityName { get; set; }
        public string SignInBranch { get; set; }
        public string SignInBranchName { get; set; }
        public string SignInCity { get; set; }
        public string SignInCityName { get; set; }
        public string SendName { get; set; }
        public string DeliveryName { get; set; }
        public string IsStraightCar { get; set; }
        public string NewActualWeight { get; set; }
        public string NewBubbleWeight { get; set; }
        public string NewSettlementWeight { get; set; }
        public string SettlementWeightType { get; set; }
        public string NewTransferCost { get; set; }
        public string TotaNewOrOld { get; set; }
        public string AdjustWay { get; set; }
        public string ErrorType { get; set; }
        public string FetchDate { get; set; }
    }
}
