//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WDTGoods
    {
        public int ID { get; set; }
        public string goods_no { get; set; }
        public string goods_name { get; set; }
        public string short_name { get; set; }
        public string alias { get; set; }
        public Nullable<int> goods_type { get; set; }
        public Nullable<int> spec_count { get; set; }
        public string pinyin { get; set; }
        public string brand_no { get; set; }
        public string brand_name { get; set; }
        public string remark { get; set; }
        public string unit_name { get; set; }
        public string origin { get; set; }
        public string class_name { get; set; }
        public string aux_unit_name { get; set; }
        public string flag_name { get; set; }
        public string spec_no { get; set; }
        public string spec_code { get; set; }
        public string barcode { get; set; }
        public string spec_name { get; set; }
        public Nullable<decimal> lowest_price { get; set; }
        public Nullable<decimal> retail_price { get; set; }
        public Nullable<decimal> wholesale_price { get; set; }
        public Nullable<decimal> member_price { get; set; }
        public Nullable<decimal> market_price { get; set; }
        public string spec_unit_name { get; set; }
        public string spec_aux_unit_name { get; set; }
    }
}
