//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WeChat
    {
        public int ID { get; set; }
        public string ShopName { get; set; }
        public string Wangwang { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string EstablishName { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string WechatNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<int> Isdelete { get; set; }
        public string Expenditure { get; set; }
        public string SystemRemarks { get; set; }
        public string iszhengc { get; set; }
    }
}
