//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Retreat
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Retreat_date { get; set; }
        public string Retreat_dianpName { get; set; }
        public string Retreat_wangwang { get; set; }
        public string Retreat_CustomerName { get; set; }
        public string Retreat_Remarks { get; set; }
        public Nullable<decimal> Retreat_Shouldjine { get; set; }
        public Nullable<decimal> Retreat_Actualjine { get; set; }
        public string Retreat_OrderNumber { get; set; }
        public string Retreat_expressName { get; set; }
        public string Retreat_expressNumber { get; set; }
        public string Retreat_GoodsSituation { get; set; }
        public string Retreat_Warehouse { get; set; }
        public string Retreat_ApplyName { get; set; }
        public string Retreat_Reason { get; set; }
        public Nullable<double> OrderMoney { get; set; }
        public Nullable<double> OrderpaymentMoney { get; set; }
        public string Retreat_PaymentAccounts { get; set; }
        public string CollectName { get; set; }
        public string CollectAddress { get; set; }
        public string Isdelete { get; set; }
        public string DeleteRemarks { get; set; }
        public string OpenPieceName { get; set; }
        public Nullable<System.DateTime> OpenPieceDate { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public string repeat { get; set; }
        public Nullable<int> isSorting { get; set; }
        public string SortingName { get; set; }
        public string isNoheadparts { get; set; }
        public string receivermobile { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OutsourcingSingle { get; set; }
        public Nullable<int> DeliverStatus { get; set; }
        public string OrderSatus { get; set; }
        public Nullable<int> IsReturn { get; set; }
        public Nullable<int> IsRefund { get; set; }
    }
}
