//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CheckAttendace
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string PostName { get; set; }
        public System.DateTime PostTime { get; set; }
        public string Reason { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> Days { get; set; }
        public Nullable<System.DateTime> WorkStartTime { get; set; }
        public Nullable<System.DateTime> WorkEndTime { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public string CurrentApprove { get; set; }
        public int IsDelete { get; set; }
        public int Mode { get; set; }
    }
}
