//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HtSuNing
    {
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public string OrderRowNum { get; set; }
        public string Channel { get; set; }
        public string OrderState { get; set; }
        public string Store { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderRequirementDate { get; set; }
        public string CustomerName { get; set; }
        public string Telephone { get; set; }
        public string CustomerRemarks { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string ShopName { get; set; }
        public int Istijiao { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
