//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AssetsApprove
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int ApplyID { get; set; }
        public string ApproveName { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public int State { get; set; }
        public string Memo { get; set; }
        public string Step { get; set; }
        public int Mode { get; set; }
        public string ApproveType { get; set; }
    }
}
