//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ExchangeCenter
    {
        public int ID { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string VipName { get; set; }
        public string VipCode { get; set; }
        public string OrderCode { get; set; }
        public string NewOrderCode { get; set; }
        public string SingleTime { get; set; }
        public string NeedOrderType { get; set; }
        public string ReturnExpressName { get; set; }
        public string ReturnExpressCode { get; set; }
        public string ReturnWarhouse { get; set; }
        public string ExchangeReson { get; set; }
        public string ReceivingName { get; set; }
        public string ReceivingPhone { get; set; }
        public string ReceivingTelPhone { get; set; }
        public string ReceivingAddress { get; set; }
        public string PostUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
        public int Step { get; set; }
        public string NeedWarhouse { get; set; }
        public string NeedExpress { get; set; }
        public string NeedPostalCode { get; set; }
        public string SalesRemark { get; set; }
        public string BuyRemark { get; set; }
        public string AddressMessage { get; set; }
        public Nullable<int> WarhouseStatus { get; set; }
        public string SystemRemark { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderScode { get; set; }
    }
}
