//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AliExpressOrder
    {
        public int ID { get; set; }
        public string state { get; set; }
        public string salesman { get; set; }
        public string buyer { get; set; }
        public string buyerMail { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public Nullable<System.DateTime> paymentTime { get; set; }
        public Nullable<double> totalProductValue { get; set; }
        public Nullable<double> logisticsCost { get; set; }
        public Nullable<double> orderMoney { get; set; }
        public Nullable<double> purchasePriceProduct { get; set; }
        public Nullable<double> platformCommission { get; set; }
        public Nullable<double> homeFreight { get; set; }
        public Nullable<double> foreignFreight { get; set; }
        public Nullable<double> profit { get; set; }
        public Nullable<double> profitRate { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> fullReduction { get; set; }
        public string productInformation { get; set; }
        public string orderRemark { get; set; }
        public string receiveAddress { get; set; }
        public string receiver { get; set; }
        public string receiveCountry { get; set; }
        public string canton { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string buyerChooseLogistics { get; set; }
        public string periodDispatch { get; set; }
        public string dispatchID { get; set; }
        public Nullable<System.DateTime> dispatchTime { get; set; }
        public Nullable<System.DateTime> confirmReceiveTime { get; set; }
        public string remark { get; set; }
        public string orderNumber { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public string isKeyuan { get; set; }
        public string isDelete { get; set; }
        public Nullable<double> refund { get; set; }
        public string refundReason { get; set; }
    }
}
