//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AliSumaiGoods
    {
        public int ID { get; set; }
        public string OrderNO { get; set; }
        public string SKU { get; set; }
        public string ProductName { get; set; }
        public string ProductNameEng { get; set; }
        public double ProductQty { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string CustomsName { get; set; }
        public string CustomsName2 { get; set; }
        public Nullable<double> DeclarationUnitPrice { get; set; }
        public string CustomsCode { get; set; }
        public string ProductSpec { get; set; }
        public Nullable<double> CustomsWeight { get; set; }
    }
}
