//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_offerDetails
    {
        public int ID { get; set; }
        public string code { get; set; }
        public string create_Name { get; set; }
        public Nullable<decimal> cost_price { get; set; }
        public Nullable<int> offerID { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<decimal> offerCost { get; set; }
    }
}
