//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EmployDemand
    {
        public int ID { get; set; }
        public string DemandUser { get; set; }
        public string DemandDepartment { get; set; }
        public string Job { get; set; }
        public int PeopleNum { get; set; }
        public string Memo { get; set; }
        public int State { get; set; }
        public string PerMemo { get; set; }
        public string RecommendSalary { get; set; }
        public int DistributionNum { get; set; }
        public string CurrentApproveName { get; set; }
        public int Step { get; set; }
        public string Recruiter { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string IsDelete { get; set; }
    }
}
