//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_goods
    {
        public int goods_id { get; set; }
        public short goods_type { get; set; }
        public string goods_no { get; set; }
        public string goods_name { get; set; }
        public string short_name { get; set; }
        public string alias { get; set; }
        public int spec_count { get; set; }
        public int class_id { get; set; }
        public int brand_id { get; set; }
        public int unit { get; set; }
        public int aux_unit { get; set; }
        public string pinyin { get; set; }
        public string origin { get; set; }
        public string remark { get; set; }
        public int flag_id { get; set; }
        public string properties { get; set; }
        public string prop1 { get; set; }
        public string prop2 { get; set; }
        public string prop3 { get; set; }
        public string prop4 { get; set; }
        public string prop5 { get; set; }
        public string prop6 { get; set; }
        public int deleted { get; set; }
        public int version_id { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual goods_brand goods_brand { get; set; }
    }
}
