//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AreaSubsidyCost
    {
        public int ID { get; set; }
        public string SettlementDate { get; set; }
        public string Number { get; set; }
        public string CheckComPany { get; set; }
        public string CheckComPanyName { get; set; }
        public string CheckChildComPany { get; set; }
        public string CheckChildComPanyName { get; set; }
        public string StartAdress { get; set; }
        public string StartAdressName { get; set; }
        public string StartAdressComPany { get; set; }
        public string StartAdressComPanyName { get; set; }
        public string StartCity { get; set; }
        public string StartCityName { get; set; }
        public string Destination { get; set; }
        public string DestinationName { get; set; }
        public string DestinationComPany { get; set; }
        public string DestinationComPanyName { get; set; }
        public string DestinationCity { get; set; }
        public string DestinationCityName { get; set; }
        public string CostCode { get; set; }
        public string CostName { get; set; }
        public string SettlementCost { get; set; }
        public string SettlementCode { get; set; }
        public string SettlementCodeName { get; set; }
        public string ConsigneeCode { get; set; }
        public string ConsigneeName { get; set; }
        public string SendCode { get; set; }
        public string SendCodeName { get; set; }
        public string ArriveDate { get; set; }
        public string SignInDate { get; set; }
    }
}
